services:
  floci:
    image: floci/floci:latest
    ports:
      - "4566:4566"
    volumes:
      - ./floci/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      AWS_DEFAULT_REGION: us-east-1
      FLOCI_STORAGE_MODE: persistent
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - floci
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:1.30.4-alpine3.24
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend
      - floci
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    name: s3-demo-upload-net
