server {
    listen 80;
    server_name s3.tharisha.site;
    location / {
        proxy_pass http://frontend:5173;
    }
    location /backend/ {
        proxy_pass http://backend:3000;
    }
    location /floci {
        proxy_pass http://floci:4566;
    }
}
