server {
    listen 80;
    server_name s3.tharisha.site;

    # redirection floci to floci ui
    location = /floci {
        return 302 http://$host:4500/;
    }
    location = /floci/ {
        return 302 http://$host:4500/;
    }

    # floci ui
    location ^~ /_floci/ {
        proxy_pass http://floci:4566;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;

    }

    location / {
        proxy_pass http://frontend:5173;
        proxy_set_header Host $host;
    }
    location /api/ {
        proxy_pass http://backend:3000/;
    }
}
